apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: b
  project: giri-stability
spec:
  artifact:
    path:
      name: file://b/b.yaml
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-mks-ns
  resourceQuotas: {}
