apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    logging.csp.vmware.com/fluentd-status: ""
  labels:
    kubernetes.io/metadata.name: calico-system
    name: calico-system
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
  name: calico-system
  project: giri-stability
spec:
  drift:
    action: Deny
    enabled: true
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-mks-ns
    - key: rafay.dev/clusterName
      value: giri-aks-stability
