apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    l2: v2
  labels:
    l1: v1
  name: git-infra-wizard
  project: giri-stability
spec:
  limitRange:
    container:
      default:
        cpu: 2u
        memory: 2047868928u
      defaultRequest:
        cpu: 1u
        memory: 1024458752u
      max:
        cpu: 2u
        memory: 2047868928u
      min:
        cpu: 1u
        memory: 1024458752u
    pod:
      max:
        cpu: 2u
        memory: 2047868928u
      min:
        cpu: 1u
        memory: 1024458752u
  namespaceMeshPolicyParams: {}
  resourceQuotas:
    configMaps: "10"
    cpuLimits: 4m
    cpuRequests: 2m
    memoryLimits: 2048Mi
    memoryRequests: 1024Mi
    persistentVolumeClaims: "10"
    pods: "10"
    replicationControllers: "10"
    secrets: "10"
    services: "10"
    servicesLoadBalancers: "10"
    servicesNodePorts: "10"
    storageRequests: 100Gi
