apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    l2: v2
  labels:
    l1: v1
  name: org-wizard
  project: giri-stability
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/logging
      value: disabled
  resourceQuotas: {}
