apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"name":"test"},"name":"pj-test"}}
  labels:
    kubernetes.io/metadata.name: pj-test
    name: test
  name: pj-test
  project: giri-stability
spec:
  drift:
    action: Deny
    enabled: true
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-mks-ns
