apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: qa
  project: giri-stability
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: env
      value: qa
  resourceQuotas: {}
