apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: stability-ns
  project: giri-stability
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-mks-ns
  resourceQuotas: {}
