apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: test
  project: giri-stability
spec:
  artifact:
    path:
      name: file://test/test.yaml
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  resourceQuotas: {}
